trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployToNginx
  jobs:
  - job: DeployToNginxJob
    steps:
    - checkout: self

    - script: |
        echo "Iniciando o estágio de deploy"
        
        # Configuração do ambiente (instalação do Nginx, por exemplo)
        sudo apt-get update
        sudo apt-get install -y nginx

        # Download do código do repositório (substitua 'sua-branch' pelo nome da sua branch)
        git checkout -b sua-branch
        git pull origin sua-branch

        # Copiar o código para o diretório do Nginx (substitua 'RvFinacer' pelo caminho real)
        sudo cp -R RvFinacer/* /var/www/html/

        # Reiniciar o Nginx para aplicar as alterações
        sudo service nginx restart

        # Exibindo o link da aplicação
        echo "Aplicação está rodando em http://localhost"
      displayName: 'Deploy'
