trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo "Iniciando o estágio de deploy"
        
        # Baixar o index.html do GitHub
        wget https://raw.githubusercontent.com/Rayan-1/appRVfinacer/main/RvFinacer/index.html -O index.html
        
        # Instalar http-server para servir a aplicação
        npm install -g http-server

        # Iniciar o servidor e atribuir uma porta
        http-server -p 8080 &

        # Aguardar alguns segundos para garantir que o servidor esteja funcionando
        sleep 10

        # Exibir o link da aplicação
        echo "Aplicação está rodando em http://localhost:8080"
      displayName: 'Deploy'
